default_install_hook_types:
  - pre-commit
  - pre-push
  - commit-msg
  - prepare-commit-msg
repos:
  - repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
    rev: v2.12.0
    hooks:
      - id: pretty-format-java
        args: [--autofix, --google-java-formatter-version=1.21.0]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
  - repo: https://github.com/compilerla/conventional-pre-commit
    rev: v2.4.0
    hooks:
      - id: "conventional-pre-commit"
    stages: [commit-msg]
    args: ["build", "ci", "docs", "feat", "fix", "refactor", "style", "test", "chore"]
